### ISSUE TITLE
Undefined prefix is being sent on WHO reply

### ISSUE THREAD

**Issue by mauriciobr** [lessandro/ircd#6]
Prefix `*` is being sent on WHO reply and is not defined on the server:
`:lessandro.com 352 adhiasdh #Lobby usrnm 127.0.0.1 lessandro.com adhiasdhla H* :0 RealName`

Defined prefixes:
`:lessandro.com 005 adhiasdh PREFIX=(qov).@+ CHANTYPES=# CHARSET=UTF-8 CHANMODES=,,,m :are supported by this server`

**Comment by lessandro** [comment]
The star [identifies IRCops](https://github.com/inspircd/inspircd/blob/master/src/coremods/core_who.cpp#L216).
